version: "3"

services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    env_file: strapi.env
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"

  db:
    image: postgres:13
    restart: unless-stopped
    shm_size: '3gb'
    volumes: 
      - db-data:/var/lib/postgresql/data
    env_file: db.env
    ports: 
     - "5432:5432"
  
  pg-admin:
    image: dpage/pgadmin4
    env_file: pgadmin.env 
    ports:
      - "80:80"

  # nginx:
  #   build:
  #     context: ./
  #     dockerfile: ./fe/Dockerfile
  #   depends_on: 
  #     - strapi
  #   volumes: 
  #     - ./nginx/:/etc/nginx/
  #     - ./certs/:/etc/nginx/ssl/
  #   ports:
  #     - "80:80"
  #     - "443:443"
volumes:
  db-data: